### ISSUE TITLE
Allow selection of custom service/service to be selected

### ISSUE THREAD

**Issue by phwecker** [bitfocus/companion-module-bmd-webpresenterhd#3]
currently only the default platforms are listed. the web presenter allows import of custom XML to load additional settings. it would be good to account for this as well and allow the stream settings operation to also set those as active.

**Comment by phwecker** [comment]
the necessary data is provided in the "Available Custom Platforms" section of the data returned from webpresenter

**Comment by daniep01** [comment]
All done and released in the beta. Thanks.
