### ISSUE TITLE
Changing Streaming settings not working. 

### ISSUE THREAD

**Issue by SamTheMD** [bitfocus/companion-module-bmd-webpresenterhd#5]
Hey there! I am trying to change stream settings on my WP4k, and the commands aren't working. I am on Companion 2.2.0 and version 3.1 on the WP.

**Comment by SamTheMD** [comment]
Updated Companion to 2.2.2 and still having the same problem.

**Comment by SamTheMD** [comment]
When I change the variables in the Web Presenter Utility, they update in the companion variables pane. Almost instantly. Still can't update from the streamdeck button though.

**Comment by daniep01** [comment]
Can you show me the settings you are trying to send. I've just retested on a WebPresenter4K and set it to YouTube without any problem.

**Comment by daniep01** [comment]
For YouTube the server needs to be either 'Primary' or 'Secondary', the same as you would see in the WebPresenter desktop app.

**Comment by SamTheMD** [comment]
Gotcha. Do i need to type "Primary" or "Secondary" instead of the URL in the server text field?

**Comment by daniep01** [comment]
Yes, the config fields in Companion should always show the same text as the WebPresenter desktop app.

**Comment by SamTheMD** [comment]
That did the trick! Thank you!
