### ISSUE TITLE
Add Stream Duration Variables

### ISSUE THREAD

**Issue by nickvanhouten** [bitfocus/companion-module-bmd-webpresenterhd#7]
Add stream duration variables a la ATEM Mini Pro integration
![Screen Shot 2022-08-11 at 7 06 43 PM](https://user-images.githubusercontent.com/65696939/184271872-2c216099-166a-407e-abfe-a516517aab4c.png)

**Comment by daniep01** [comment]
This looks possible, it will take me a few days

**Comment by daniep01** [comment]
This will be in thew next beta release
