### ISSUE TITLE
WebPresenter: Stream Settings

### ISSUE THREAD

**Issue by TylerFerren** [bitfocus/companion-module-bmd-webpresenterhd#8]
WebPresenter: Stream Settings only adjust the video output stream standard (resolution and frame rate) but does not change the platform, Key, or quality.

**Comment by daniep01** [comment]
Which version/build of companion are you using?

**Comment by TylerFerren** [comment]
2.4.1

**Comment by daniep01** [comment]
I'm sorry but I can't reproduce the issue, it's working fine for me.

![anydesk00000](https://user-images.githubusercontent.com/17852298/213880494-68bf6ea6-5ad9-401f-91eb-80518afe74df.png)
