### ISSUE TITLE
Feature request: Lock toggle

### ISSUE THREAD

**Issue by LHasenbein** [bitfocus/companion-module-bmd-webpresenterhd#9]
Thanks for this nice module. It is very useful for our work. We would find it very helpful if we could also lock / unlock the device.

**Comment by daniep01** [comment]
I've checked the manual and sadly I don't think the Lock  feature exists in the Web Presenter API so it can't be turned on or off remotely.

**Comment by LHasenbein** [comment]
@daniep01 Ah ok, I see. Too bad, but thanks for your efforts.
